name: 'NCP Cloud Edge Purge'
description: 'Purge NCP Cloud Edge Cache'
inputs:
  ncp-access-key-id:
    description: 'NCP Access Key ID'
    required: true
  ncp-secret-key:
    description: 'NCP Secret Key'
    required: true
  edge-profile-id:
    description: 'NCP Cloud Edge Profile ID'
    required: true
  edge-id:
    description: 'NCP Cloud Edge ID'
    required: true
  purge-type:
    description: 'Purge Type(ex. ALL, DIRECTORY, PATTERN, URL)'
    required: true
    default: 'ALL'
  purge-target:
    description: 'Purge Target (ref. https://api.ncloud-docs.com/docs/en/purge-request)'
    required: false
outputs:
  purge_request_ids: # id of output
    description: 'Purge Request IDs'
runs:
  using: 'node20'
  main: 'index.js'
