name: ncp-cloud-edge-purge-test
on:
  workflow_dispatch:
jobs:
  purge-test:
    runs-on: ubuntu-latest
    steps:
      - uses: pilltong-dev/ncp-cloud-edge-purge@v0.1
        with:
          ncp-access-key-id: '#########'
          ncp-secret-key: '#########'
          edge-profile-id: 'my-edge-profile-id'
          edge-id: 'my-edge-id'
